name = "sechurra"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "c0dd9240620a4093916e7f25014c788e"

